/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi_koperasi;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author enoh
 */
public class Aplikasi_Menu_Utama extends javax.swing.JFrame {
koneksi kon = new koneksi();
public Aplikasi_Lupa_Password lupa_Password=null;
    /**
     * Creates new form Aplikasi_Menu_Utama
     */
    public Aplikasi_Menu_Utama() {
        initComponents();
        kon.setKoneksi();
    }
    
    public String KodeUser;
    public String Level;
    public String NamaUser;
    public String getKodeUser()
                {
                    return KodeUser;
                }
    
    public String getNamaUser()
                {
                    return NamaUser;
                }
    
    public String getLevel()
                {
                    return Level;
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        bt_transaksi = new javax.swing.JButton();
        bt_simpanan = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        bt_anggota = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        l_kode = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        l_level = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        l_nama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnUser = new javax.swing.JMenuItem();
        mnAnggota = new javax.swing.JMenuItem();
        mnSimpanan = new javax.swing.JMenuItem();
        mntransaksi = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        MnLapPinjaman = new javax.swing.JMenuItem();
        mnLapAnggota = new javax.swing.JMenuItem();
        mnLapSimpanan = new javax.swing.JMenuItem();
        mnLapUser = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnGantiPass = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 730, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 20));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 20, 380));

        bt_transaksi.setText("Transaksi");
        bt_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(bt_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));

        bt_simpanan.setText("Simpanan");
        bt_simpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpananActionPerformed(evt);
            }
        });
        getContentPane().add(bt_simpanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_koperasi/img/Actions-application-exit-icon.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 30, 30));

        bt_anggota.setText("Anggota");
        bt_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_anggotaActionPerformed(evt);
            }
        });
        getContentPane().add(bt_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, -1));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setForeground(new java.awt.Color(225, 26, 26));
        jLabel3.setText("User Code");

        l_kode.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_kode)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(l_kode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 150, 30));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setForeground(new java.awt.Color(233, 14, 14));
        jLabel4.setText("Acces Level");

        l_level.setText("jLabel7");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_level)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(l_level))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 150, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anggota Kelompok", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel5.setForeground(new java.awt.Color(225, 22, 22));
        jLabel5.setText("Enoh Badri");

        jLabel6.setForeground(new java.awt.Color(215, 28, 28));
        jLabel6.setText("Saadudin Kamal");

        jLabel7.setForeground(new java.awt.Color(230, 25, 25));
        jLabel7.setText("Fazri Aditiya P");

        jLabel8.setForeground(new java.awt.Color(238, 25, 25));
        jLabel8.setText("Hefi Agung W");

        jLabel9.setForeground(new java.awt.Color(235, 28, 28));
        jLabel9.setText("Lilis Siti N");

        jLabel10.setForeground(new java.awt.Color(240, 15, 15));
        jLabel10.setText("Marisa Apriani");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, 210));

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel11.setText("KOPERASI SIMPAN PINJAM");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setForeground(new java.awt.Color(232, 19, 19));
        jLabel2.setText("Welcome");

        l_nama.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(l_nama)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(l_nama))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi_koperasi/img/JAVA-768x432.jpg"))); // NOI18N
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabel1FocusLost(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 729, -1));

        jMenu1.setText("System");

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnLogout);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");

        mnUser.setText("User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        jMenu2.add(mnUser);

        mnAnggota.setText("Anggota");
        mnAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAnggotaActionPerformed(evt);
            }
        });
        jMenu2.add(mnAnggota);

        mnSimpanan.setText("Simpanan");
        mnSimpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSimpananActionPerformed(evt);
            }
        });
        jMenu2.add(mnSimpanan);

        jMenuBar1.add(jMenu2);

        mntransaksi.setText("Transaksi");
        mntransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mntransaksiMouseClicked(evt);
            }
        });
        jMenuBar1.add(mntransaksi);

        jMenu4.setText("Laporan");

        MnLapPinjaman.setText("Lap Pinjaman");
        MnLapPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLapPinjamanActionPerformed(evt);
            }
        });
        jMenu4.add(MnLapPinjaman);

        mnLapAnggota.setText("Lap Anggota");
        mnLapAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapAnggotaActionPerformed(evt);
            }
        });
        jMenu4.add(mnLapAnggota);

        mnLapSimpanan.setText("Lap Simpanan");
        mnLapSimpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapSimpananActionPerformed(evt);
            }
        });
        jMenu4.add(mnLapSimpanan);

        mnLapUser.setText("Lap User");
        mnLapUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapUserActionPerformed(evt);
            }
        });
        jMenu4.add(mnLapUser);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Utility");

        mnGantiPass.setText("Ganti Password");
        mnGantiPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGantiPassActionPerformed(evt);
            }
        });
        jMenu5.add(mnGantiPass);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Help");

        mnAbout.setText("About");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenu6.add(mnAbout);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Aplikasi_Login login = new Aplikasi_Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        // TODO add your handling code here:
        Aplikasi_Master_User user = new Aplikasi_Master_User();
        user.setLocationRelativeTo(null);
        user.setVisible(true);
    }//GEN-LAST:event_mnUserActionPerformed

    private void mnAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAnggotaActionPerformed
        // TODO add your handling code here:
        Aplikasi_Master_Anggota Anggota = new Aplikasi_Master_Anggota();
        Anggota.setLocationRelativeTo(null);
        Anggota.setVisible(true);
    }//GEN-LAST:event_mnAnggotaActionPerformed

    private void mnSimpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSimpananActionPerformed
        // TODO add your handling code here:
        Aplikasi_Master_Simpanan Simpanan = new Aplikasi_Master_Simpanan();
        Simpanan.setLocationRelativeTo(null);
        Simpanan.setVisible(true);
    }//GEN-LAST:event_mnSimpananActionPerformed

    private void mnGantiPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGantiPassActionPerformed
        // TODO add your handling code here:
        Aplikasi_Lupa_Password gantiPass = new Aplikasi_Lupa_Password();
        gantiPass.setLocationRelativeTo(null);
        gantiPass.setVisible(true);
        gantiPass.Kode_User=l_kode.getText();
    }//GEN-LAST:event_mnGantiPassActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        l_nama.setText(NamaUser);
        l_kode.setText(KodeUser);
        l_level.setText(Level);
    }//GEN-LAST:event_formWindowActivated

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        // TODO add your handling code here:
        Tentang_Aplikasi about = new Tentang_Aplikasi();
        about.setLocationRelativeTo(null);
        about.setVisible(true);
    }//GEN-LAST:event_mnAboutActionPerformed

    private void mntransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mntransaksiMouseClicked
        // TODO add your handling code here:
        Aplikasi_Transaksi transaksi = new Aplikasi_Transaksi();
        transaksi.setLocationRelativeTo(null);
        transaksi.setVisible(true);
        transaksi.KodeUser=l_kode.getText();
    }//GEN-LAST:event_mntransaksiMouseClicked

    private void mnLapAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapAnggotaActionPerformed
        // TODO add your handling code here:
        try {
            String path="src/aplikasi_koperasi/Laporan_Anggota.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, kon.setKoneksi());
            JasperViewer.viewReport(print, false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mnLapAnggotaActionPerformed

    private void bt_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_anggotaActionPerformed
        // TODO add your handling code here:
        Aplikasi_Master_Anggota xx;
        xx = new Aplikasi_Master_Anggota();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_anggotaActionPerformed

    private void bt_simpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpananActionPerformed
        // TODO add your handling code here:
        Aplikasi_Master_Simpanan xx;
        xx = new Aplikasi_Master_Simpanan();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_simpananActionPerformed

    private void bt_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_transaksiActionPerformed
        // TODO add your handling code here:
        Aplikasi_Transaksi xx;
        xx = new Aplikasi_Transaksi();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_transaksiActionPerformed

    private void MnLapPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLapPinjamanActionPerformed
        // TODO add your handling code here:
         try {
            String path="src/aplikasi_koperasi/Laporan_Pinjaman.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, kon.setKoneksi());
            JasperViewer.viewReport(print, false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_MnLapPinjamanActionPerformed

    private void mnLapSimpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapSimpananActionPerformed
        // TODO add your handling code here:
         try {
            String path="src/aplikasi_koperasi/Laporan_Simpanan.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, kon.setKoneksi());
            JasperViewer.viewReport(print, false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mnLapSimpananActionPerformed

    private void mnLapUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapUserActionPerformed
        // TODO add your handling code here:
         try {
            String path="src/aplikasi_koperasi/Laporan_User.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, kon.setKoneksi());
            JasperViewer.viewReport(print, false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mnLapUserActionPerformed

    private void jLabel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikasi_Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnLapPinjaman;
    private javax.swing.JButton bt_anggota;
    private javax.swing.JButton bt_simpanan;
    private javax.swing.JButton bt_transaksi;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel l_kode;
    private javax.swing.JLabel l_level;
    private javax.swing.JLabel l_nama;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenuItem mnAnggota;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnGantiPass;
    private javax.swing.JMenuItem mnLapAnggota;
    private javax.swing.JMenuItem mnLapSimpanan;
    private javax.swing.JMenuItem mnLapUser;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnSimpanan;
    private javax.swing.JMenuItem mnUser;
    private javax.swing.JMenu mntransaksi;
    // End of variables declaration//GEN-END:variables
}
